[options]
admin_passwd = $pbkdf2-sha512$600000$2TvHOAcgpLS2VkoJgVCKUQ$PN.SK3cPVpWqF90s2L3d6rEw12CG7DcmLIS5vQdx03VGuENAH9Y.c2w1MDy/cD9pf2GEePebmtEu4ZGtpygjhg
db_host = False
db_port = False
db_user = odoo
db_password = False
addons_path = /Users/priya/Documents/Projects/odoo19/OdooFBR/odoo/addons,/Users/priya/Documents/Projects/odoo19/OdooFBR/odoo/fbr_addons

default_productivity_apps = True
